#!/usr/bin/env bash
# Setups the repository.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

python3 -m venv venv
source venv/bin/activate

pip install wheel
pip install -r requirements.test.txt

pre-commit install
